version: "2"
checks:
plugins:
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - BUG
      - TODO
      - HACK
  markdownlint:
    enabled: true
exclude_patterns:
  - "public/"
  - "node_modules/"
  - ".cache/"
  - "*.log*"
