# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/
  
stages:
  - test
  - build
  - deploy

test:
  script:
   - npm install
   # TODO: Run tests here
   - echo "Testing..."

build_prod:
  stage: build
  script:
  ##
  ## Ensure we're starting fresh
  ##
  - unset PUBLIC_URL

  ##
  ## Install dependencies and build the production site
  ##
  - npm install # Install all dependencies
  - npm run build # Build for production
  artifacts:
    paths:
      - public
  only:
    - master

# Job name for gitlab to recognise this results in assets for Gitlab Pages
# https://docs.gitlab.com/ee/user/project/pages/introduction.html#gitlab-pages-requirements
deploy_pages:
  stage: deploy
  variables:
    PUBLIC_URL: /portfolio
  script:
    - npm install # Install all dependencies
    - npm run build --prefix-paths # Build for production
  artifacts:
    paths:
    - public # The built files for Gitlab Pages to serve

deploy_prod:
  stage: deploy
  tags:
    - deploy
  script:
    - sudo cp -r public/* /srv/vondenstein.com/
  environment:
    name: production
    url: https://vondenstein.com
  only:
    - master

